version: "3"

services:
  db:
    container_name: ${ENV_DB_CONTAINER_NAME}
    build: ./db/
    image: ${ENV_DB_IMAGE_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${ENV_DB_DATABASE}
      MYSQL_USER: ${ENV_DB_USERNAME}
      MYSQL_PASSWORD: ${ENV_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
      TZ: ${ENV_TIMEZONE}
    ports:
      - ${ENV_DB_PORT}:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - app_net
  app:
    container_name: ${ENV_APP_CONTAINER_NAME}
    build:
      context: ./app/
      args:
        ENV_DB_CONNECTION: ${ENV_DB_CONNECTION}
        ENV_DB_HOST: ${ENV_DB_HOST}
        ENV_DB_PORT: ${ENV_DB_PORT}
        ENV_DB_DATABASE: ${ENV_DB_DATABASE}
        ENV_DB_USERNAME: ${ENV_DB_USERNAME}
        ENV_DB_PASSWORD: ${ENV_DB_PASSWORD}
        ENV_DB_ROOT_PASSWORD: ${ENV_DB_ROOT_PASSWORD}
        ENV_DOCUMENT_ROOT: ${ENV_DOCUMENT_ROOT}
        ENV_SRC_DIRECTORY_NAME: ${ENV_SRC_DIRECTORY_NAME}
    image: ${ENV_APP_IMAGE_NAME}
    restart: always
    env_file:
      - ./.env
    ports:
      - ${ENV_APP_PORT}:80
    links:
      - db
    volumes:
      - ../project/${ENV_SRC_DIRECTORY_NAME}:${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}
      # 1. exclude volumes
      - ${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}/vendor
      - ${ENV_DOCUMENT_ROOT}/${ENV_SRC_DIRECTORY_NAME}/node_modules
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge